x-app: &default-app
  build: .
  volumes:
    - .:/app
  env_file:
    - .env

services:
  mysql_db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  web:
    <<: *default-app
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy
    links:
      - mysql_db

  tailwind:
    <<: *default-app
    command: "python manage.py tailwind start"
    tty: true
    depends_on:
      - web

volumes:
  mysql_data:
