# Generated by Django 5.0.6 on 2025-01-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_profile_picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
