# Generated by Django 5.0.6 on 2025-01-08 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_created_at_subject_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description_de',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_es',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_fr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(-1, 'Left winged'), (1, 'Right winged')]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('subject', 'user')},
        ),
    ]
